name: CI

on:
  [pull_request, workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test:cov
      - run: npm run test:e2e

      - name: The eslint checking
        run: npm run lint